### ISSUE TITLE
Choix du sujet, utilité sociale, effet de la numérisation

### ISSUE THREAD

**Issue by benel** [UTT-GL03/EduNova#2]
Merci pour votre première livraison (choix du sujet, utilité sociale, effet de la numérisation).

Quelques points d'attention...

"diverses loisirs" -> "divers loisirs"

"est représente" -> "représente"

"pour nous une activité fréquente et indispensable" : pouvez-vous expliciter, donner des exemples ?

Attention à la typographie des listes. Le texte mis en forme doit rester une phrase : 
- avec un point à la fin du dernier item,
- avec une virgule (ou un point virgule) à la fin des autres items.

💵 🏢 📈🚗 🚝 ✈️ : Vous venez de découvrir les emojis ;)

"tendraient" -> "tendrait"

Si vous tenez vraiment à garder l'idée du divertissement numérique par l'apprentissage numérique, il va falloir des arguments plus précis et plus convaincants...

De manière générale, je vous invite à relire voire à tester vos argument sur des connaissances.

Merci d'avance.

**Comment by TheoM769** [comment]
Bonjour,

Nous avons bien pris en compte votre retour. Nous avons corrigé les fautes et le format, ainsi que supprimé notre argument sur le divertissement (complexe à chiffrer).

**Comment by benel** [comment]
Merci @TheoM769 et @Louis-Gv. Vous avez effectivement réglé la plupart de mes remarques.

Il reste quelques coquilles typographiques : espaces autour de deux points, phrase avec double deux-points, majuscules mal placées. Peut-être que vous pouvez copier-coller le texte dans un traitement de texte pour détecter tous ces petits problèmes...

Concernant les emojis, je ne veux pas brider votre créativité, mais le résultat fait quand même plus livre pour enfant que rapport de conception...

**Comment by TheoM769** [comment]
Bonjour,

Je pense avoir réglé tous les problèmes de syntaxe, et j'ai enlevé les émojis pour apporter plus de sérieux à notre ReadMe. N'hésitez pas si vous avez d'autres remarques.

**Comment by benel** [comment]
Merci de vos modifications.

Puisque vous en parlez, même si ce n'est pas très grave (ça ne vous empêche pas d'avoir le badge, c'est juste pour la note du rendu final) : 
- "Nous serons, en tant que futurs ingénieurs" : ça fait beaucoup de futurs... Vous êtes de **futurs** ingénieurs, et vous **serez** des ingénieurs.
- "support (papier ou numériques)" : petit problème d'accord..
- "au format utilisé" : j'imagine que vous pensiez plutôt au codec, expliciter pourquoi,
- "tradeoff" éviter l'anglicisme,
- "épuration" : ce terme a pris au siècle dernier une connotation horrible,
- "à proposer des solutions de téléchargement plutôt que de streaming" : expliquer rapidement pourquoi et dans quels cas,
- "héberger le contenu au plus près de l'utilisateur" : *idem*,
- "à des pôles géographiques qui mutualisent les diffusions pour limiter l’effet rebond" : que voulez vous dire par là ? je ne suis pas sûr d'avoir compris.
