### ISSUE TITLE
Scénarios et résultats des tests

### ISSUE THREAD

**Issue by benel** [UTT-GL03/EduNova#3]
Merci pour le second livrable (scénarios et résultats des tests).

C'est intéressant mais il y a des améliorations à apporter :

- pensez à présenter (et référencer) vos scénarios et vos résultats dans le README,
- adoptez peut-être une autre couleur pour les E (sinon tout est rouge),
- renommez les étapes pour que ce soit une action finalisée (c.-à-d. avec un but) de l'usager.

**Comment by Louis-Gv** [comment]
Bonjour nous avons fait les modifications dans le commit ci-dessus ([736aa81](https://github.com/UTT-GL03/EduNova/commit/736aa813ac4252ecec693ae073cca511c35881d4))

**Comment by benel** [comment]
Merci.
